# Generated by Django 5.1.4 on 2025-01-08 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapplication', '0002_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='job_description',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=30)),
                ('notice_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapplication.user')),
            ],
        ),
    ]
