# Generated by Django 5.1.4 on 2025-01-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapplication', '0003_alter_members_job_description_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='notice',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_title',
            field=models.CharField(max_length=255),
        ),
    ]
