# Generated by Django 5.1.4 on 2025-01-20 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapplication', '0007_rename_date_event_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapplication.members'),
        ),
        migrations.AddField(
            model_name='event',
            name='chairman',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapplication.chairman'),
        ),
    ]
