# Generated by Django 5.1.4 on 2025-01-20 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapplication', '0008_complaint_member_event_chairman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='chairman',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapplication.user'),
        ),
    ]
