# Generated by Django 5.1.4 on 2025-01-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapplication', '0009_alter_event_chairman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='chairman',
            new_name='user',
        ),
    ]
