# Generated by Django 5.1.4 on 2025-01-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapplication', '0011_event_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='title',
            new_name='complaint_title',
        ),
    ]
