# Generated by Django 5.1.4 on 2025-01-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapplication', '0013_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
